apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-rabbitmq-gs
spec:
  title: Getting Started with RabbitMQ
  description: A getting started guide for rabbitMQ
  vendor: eduk8s.io
  difficulty: beginner
  duration: 65m
  url: github.com/everythingeverywhere/lab-rabbitmq-gs
  content:
    image: quay.io/eduk8s/jdk8-environment:master
    files: github.com/everythingeverywhere/lab-rabbitmq-gs
  session:
    objects:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: rabbitmq
      spec:
        replicas: 1
        selector:
          matchLabels:
            deployment: rabbitmq
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              deployment: rabbitmq
          spec:
            containers:
            - name: rabbitmq
              image: registry.hub.docker.com/library/rabbitmq:3.8.5
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 5672
                protocol: TCP
    - apiVersion: v1
      kind: Service
      metadata:
        name: rabbitmq
      spec:
        type: ClusterIP
        ports:
        - port: 80
          targetPort: 5672
        selector:
          deployment: rabbitmq