apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-rabbitmq-gs
spec:
  title: Getting Started with RabbitMQ
  description: A getting started guide for rabbitMQ
  vendor: eduk8s.io
  difficulty: beginner
  duration: 65m
  url: github.com/everythingeverywhere/lab-rabbitmq-gs
  content:
    image: quay.io/eduk8s/jdk8-environment:master
    files: github.com/everythingeverywhere/lab-rabbitmq-gs
  session:
    budget: medium
    applications:
      console:
        enabled: true
      editor:
        enabled: true
